# numpy.array 基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.3'

## 1. Python List 特点

In [3]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
L[5]

5

In [5]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

#### python list对类型不做限定，而且在同一list中，每一个元素类型可以不同
#### 因此效率低，因为需要检查每个元素的类型

In [6]:
import array

In [7]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### array 限定类型，相对效率较高
#### 缺点：没有为数据配备向量或矩阵相关的运算

## 2. numpy.array

In [8]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
nparr[5]

5

In [10]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [11]:
nparr.dtype ##data type

dtype('int32')

In [12]:
nparr2 = np.array([1,2,3.0])

In [13]:
nparr2.dtype

dtype('float64')

## 3. 其他创建numpy.array的方法

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10).dtype

dtype('float64')

In [16]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arrange

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 并且numpy.arange 步长可为浮点数 （对比range）

In [22]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [24]:
np.linspace(0,20,10) ##在0-20 等长截出10个点

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [25]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [26]:
np.random.randint(0,10)

8

In [27]:
np.random.randint(0,10,10)

array([0, 7, 8, 4, 4, 1, 7, 9, 5, 5])

In [28]:
np.random.randint(0,1,10) ##取不到1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.random.randint(4,8,size=(3,5))

array([[7, 4, 4, 4, 5],
       [6, 6, 7, 6, 5],
       [4, 6, 7, 6, 7]])

In [30]:
np.random.seed(666) ##随机种子

In [31]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [32]:
np.random.seed(666)

In [33]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [34]:
np.random.random()

0.2811684913927954

In [35]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [36]:
np.random.random((3,5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [37]:
np.random.normal(10,100) ##均值为10 方差为100

87.60516793129695

In [38]:
np.random.normal(0,1,(3,5))

array([[ 1.18063598,  0.06102404,  1.07856138, -0.79783572,  1.1701326 ],
       [ 0.1121217 ,  0.03185388, -0.19206285,  0.78611284, -1.69046314],
       [-0.98873907,  0.31398563,  0.39638567,  0.57656584, -0.07019407]])

In [39]:
np.random.normal?

In [40]:
np.random?

In [41]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

## 4. numpy.array 基本操作

In [42]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [44]:
x.ndim

1

In [45]:
X.ndim

2

In [46]:
x.shape

(10,)

In [47]:
X.shape

(3, 5)

In [48]:
x.size

10

In [49]:
X.size

15

### np.array数据访问

In [50]:
x[0]

0

In [51]:
x[-1]

9

In [52]:
X[0][0]

0

In [53]:
X[(2,2)]

12

In [54]:
X[2,2]

12

In [55]:
x[0:5]

array([0, 1, 2, 3, 4])

In [56]:
x[:5]

array([0, 1, 2, 3, 4])

In [57]:
x[5:]

array([5, 6, 7, 8, 9])

In [58]:
x[::2]

array([0, 2, 4, 6, 8])

In [59]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [61]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [62]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [63]:
X[:,0]

array([ 0,  5, 10])

In [64]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 子矩阵通过引用获得，因此改变子矩阵也会改变原矩阵

In [65]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [66]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [67]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [68]:
X[0,0] = 0

In [69]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [70]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

#### 取copy

### reshape

In [71]:
x.shape

(10,)

In [72]:
x.ndim

1

In [73]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
x  ##没有改变自身

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
B = x.reshape(1,10) ##改二维,第一个维度是1
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [78]:
B.ndim

2

In [79]:
x.reshape(10,-1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [81]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 5. 合并与分割

### 合并

In [82]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [83]:
x

array([1, 2, 3])

In [84]:
y

array([3, 2, 1])

In [85]:
np.concatenate([x,y]) #拼接

array([1, 2, 3, 3, 2, 1])

In [86]:
z = np.array([666,666,666])

In [87]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [88]:
A = np.array([[1,2,3],
             [4,5,6]])

In [89]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [90]:
np.concatenate([A,A],axis=1) #沿着第二个维度拼接

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [91]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [92]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [93]:
np.vstack([A,z])  #在垂直方向叠加

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [94]:
B= np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [95]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割

In [96]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
x1,x2,x3 = np.split(x,[3,7])

In [98]:
x1

array([0, 1, 2])

In [99]:
x2

array([3, 4, 5, 6])

In [100]:
x3

array([7, 8, 9])

In [101]:
x1, x2 = np.split(x,[5])

In [102]:
x1

array([0, 1, 2, 3, 4])

In [103]:
x2

array([5, 6, 7, 8, 9])

In [104]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
A1, A2 = np.split(A,[2])

In [106]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [107]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
A1, A2 = np.split(A,[2], axis=1)

In [109]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [110]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [111]:
upper, lower = np.vsplit(A,[2])

In [112]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [113]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
left, right = np.hsplit(A,[2])

In [115]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [116]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## 6. numpy.array中的运算

In [117]:
n = 10
L = [i for i in range(n)]

In [118]:
2 * L #将2个L首尾衔接

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [119]:
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [120]:
A = np.array(2*e for e in L) #快

In [121]:
L = np.arange(n)

In [122]:
A = 2*L
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### numpy 把他们当作向量或矩阵看待，支持矩阵运算，并优化

### Universal Functions

In [123]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [124]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [125]:
X -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [127]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [128]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [129]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [130]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [131]:
1 /X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [132]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [133]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [134]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [135]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [136]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [137]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [138]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [139]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [140]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [141]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵之间运算

In [142]:
A= np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [143]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [144]:
A + B

array([[10, 11],
       [12, 13]])

In [145]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [146]:
A * B ## 对应元素相乘

array([[ 0, 10],
       [20, 30]])

In [147]:
A /B

array([[0. , 0.1],
       [0.2, 0.3]])

In [148]:
A.dot(B) # 矩阵点乘

array([[10, 10],
       [50, 50]])

In [149]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵运算

In [150]:
v = np.array([1,2])

In [151]:
A

array([[0, 1],
       [2, 3]])

In [152]:
v + A

array([[1, 3],
       [3, 5]])

In [154]:
np.vstack([v]* A.shape[0])

array([[1, 2],
       [1, 2]])

In [156]:
np.tile(v,(2,1)) #堆叠

array([[1, 2],
       [1, 2]])

In [157]:
v

array([1, 2])

In [158]:
A

array([[0, 1],
       [2, 3]])

In [159]:
v * A

array([[0, 2],
       [2, 6]])

In [160]:
v.dot(A)

array([4, 7])

In [161]:
A.dot(v)

array([2, 8])

### 矩阵的逆

In [162]:
A

array([[0, 1],
       [2, 3]])

In [163]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [164]:
invA = np.linalg.inv(A)

In [165]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [166]:
np.linalg.pinv(A) ## 伪逆矩阵

array([[-1.50000000e+00,  5.00000000e-01],
       [ 1.00000000e+00,  4.21097322e-17]])

## 7. 聚合操作

In [167]:
L = np.random.random(10)
L

array([0.73353358, 0.71210247, 0.2427146 , 0.57043673, 0.57773404,
       0.89274848, 0.12138544, 0.66083873, 0.16459271, 0.09435837])

In [168]:
sum(L)

4.770445149897662

In [169]:
np.sum(L)

4.770445149897662

In [170]:
np.min(L)

0.09435837471396691

In [171]:
np.max(L)

0.8927484785341333

In [172]:
L.min()

0.09435837471396691

In [173]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [174]:
np.sum(X)

120

In [175]:
np.sum(X,axis = 0)

array([24, 28, 32, 36])

In [176]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [177]:
np.prod(X)

0

In [178]:
np.prod(X+1)

2004189184

In [179]:
np.mean(X)

7.5

In [181]:
np.median(X)

7.5

In [182]:
np.percentile(X,q=50) #这个矩阵中 50%小于q

7.5

In [183]:
for percent in [0,25,50,75,100]:
    print(np.percentile(X,q=percent))

0.0
3.75
7.5
11.25
15.0


In [184]:
np.var(X) #方差

21.25

In [185]:
np.std(X) #标准差

4.6097722286464435

In [2]:
x = np.random.normal(0,1,size=1000000)

In [187]:
x.mean()

0.0003468452679831948

In [188]:
x.std()

0.999311097674792

## 8. 索引

In [3]:
np.min(x)

-5.193626630348038

In [4]:
np.argmin(x)  #索引值

664682

In [5]:
x[664682]

-5.193626630348038

In [6]:
np.argmax(x)

461798

### 排序和使用索引

In [7]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
np.random.shuffle(x)
x

array([ 7,  0,  1,  9,  5,  2,  6,  8,  4, 10,  3, 15, 13, 14, 11, 12])

In [11]:
np.sort(x) #没有改变x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x

array([ 7,  0,  1,  9,  5,  2,  6,  8,  4, 10,  3, 15, 13, 14, 11, 12])

In [13]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
X = np.random.randint(10,size=(4,4))
X

array([[2, 2, 3, 4],
       [5, 8, 9, 0],
       [4, 4, 1, 9],
       [1, 0, 7, 5]])

In [15]:
np.sort(X)

array([[2, 2, 3, 4],
       [0, 5, 8, 9],
       [1, 4, 4, 9],
       [0, 1, 5, 7]])

In [16]:
np.sort(X,axis=1)

array([[2, 2, 3, 4],
       [0, 5, 8, 9],
       [1, 4, 4, 9],
       [0, 1, 5, 7]])

In [17]:
np.sort(X,axis=0)

array([[1, 0, 1, 0],
       [2, 2, 3, 4],
       [4, 4, 7, 5],
       [5, 8, 9, 9]])

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.random.shuffle(x)
x

array([ 6,  2,  8, 15,  3, 11,  5,  1, 14, 10, 13,  0,  7,  4,  9, 12])

In [20]:
np.argsort(x)

array([11,  7,  1,  4, 13,  6,  0, 12,  2, 14,  9,  5, 15, 10,  8,  3],
      dtype=int64)

In [21]:
np.partition(x,3)

array([ 1,  0,  2,  3,  4,  5,  6, 11, 14, 10, 13, 15,  7,  8,  9, 12])

In [22]:
np.argpartition(x,3)

array([ 7, 11,  1,  4, 13,  6,  0,  5,  8,  9, 10,  3, 12,  2, 14, 15],
      dtype=int64)

In [23]:
X

array([[2, 2, 3, 4],
       [5, 8, 9, 0],
       [4, 4, 1, 9],
       [1, 0, 7, 5]])

In [24]:
np.argsort(X)

array([[0, 1, 2, 3],
       [3, 0, 1, 2],
       [2, 0, 1, 3],
       [1, 0, 3, 2]], dtype=int64)

In [25]:
np.argpartition(X,2,axis=1)

array([[0, 1, 2, 3],
       [3, 0, 1, 2],
       [2, 1, 0, 3],
       [1, 0, 3, 2]], dtype=int64)

## 9. Fancy Indexing

In [26]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
x[3]

3

In [28]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [29]:
x[3:9:2]

array([3, 5, 7])

In [30]:
ind = [3,5,8]
x[ind]

array([3, 5, 8])

In [31]:
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [32]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [34]:
X[0,col]

array([1, 2, 3])

In [35]:
col = [True,False,True,True]
X[0,col]

array([0, 2, 3])

### numpy.array 比较

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [38]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [39]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [40]:
2 * x == 24 - 4 *x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [41]:
np.sum(x <=3)

4

In [42]:
np.any(x == 0)

True

In [43]:
np.all(x >= 0)

True

In [44]:
np.any(x < 0)

False

In [45]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.sum(X%2==0)

8

In [47]:
np.sum(X%2==0, axis=1)

array([2, 2, 2, 2])